version: '3.1'

services:

  osrm-manager:
    build:
      context: ../
      dockerfile: docker/osrm-manager/Dockerfile
    ports:
      - "127.0.0.1:8088:8000"
    volumes:
      - ./data:/data
    links:
      - redis
    environment:
      - CELERY_REDIS_HOST=redis
      - OSRM_INITIAL_CONTRACT=false

  # Redis is required for Celery backend
  redis:
    image: redis:4-alpine
