variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2

stages:
    - lint
    - test
    - build

black:
    stage: lint

    only:
        - tags
        - branches

    image: python:3.6-stretch

    script:
        - pip install black
        - black --check ./

pylint:
    stage: lint

    only:
        - tags
        - branches

    image: python:3.6-stretch

    script:
        - pip install pipenv
        - pipenv sync --dev
        - pipenv run pylint -d fixme osrm tests

test:
    stage: test

    only:
        - tags
        - branches

    image: gitlab/dind

    services:
        - docker:18.09-dind

    script:
        - cd tests
        - docker-compose build test
        - docker-compose run --rm test
        - docker-compose down --volumes

build:
    stage: build

    only:
        - tags

    image: docker:stable

    services:
        - docker:18.09-dind

    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker pull $CI_REGISTRY_IMAGE:latest || true
        - |
          docker build --file docker/osrm-manager/Dockerfile \
                       --cache-from $CI_REGISTRY_IMAGE:latest \
                       --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG \
                       --tag $CI_REGISTRY_IMAGE:latest .
        - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
        - docker push $CI_REGISTRY_IMAGE:latest
